[build-system]
requires = ["setuptools>=61", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "detikzify"
readme = "README.md"
license = {text = "Apache-2.0 License"}
dependencies = [
  "torch~=2.2.1",
  "transformers[accelerate,tokenizers]~=4.38.1; platform_system != 'Darwin'",
  "transformers[accelerate,tokenizers]==4.38.1; platform_system == 'Darwin'",
  "diffusers~=0.26.3",
  "datasets~=2.17.1",
  "timm~=0.9.16",
  "Pillow~=10.2.0",
  "requests~=2.31.0",
  "numpy==1.*",
  # pdf
  "PyMuPDF~=1.23.25",
  "pdf2image~=1.17.0",
  "pdfCropMargins~=2.0.3",
  # webui
  "gradio~=4.36.0",
  "fastapi~=0.112.4", # https://github.com/gradio-app/gradio/issues/9278
  # evaluate
  "POT~=0.9.3",
  "torchmetrics~=1.3.2",
]
requires-python = "~=3.10"
dynamic = ["version"]

[project.optional-dependencies]
evaluate = [
  "Pygments~=2.17.2",
  "crystalbleu~=0.1.0",
  "sacremoses~=0.1.1",
  "dreamsim~=0.1.3"
]
deepspeed = [
  "deepspeed~=0.13.4"
]

[project.urls]
repository = "https://github.com/potamides/DeTikZify"

[tool.setuptools_scm]
write_to = "detikzify/_version.py"
parentdir_prefix_version = "detikzify-"

[tool.setuptools.packages.find]
include = ["detikzify*"]
